import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import Header from "./components/headers/Header";
import Navigation from "./components/navigation/Navigation";
import BootstrapClient from "./components/bootstrap/BootstrapClient";
import { UserProvider } from "./UserContext";
import Clock from "./components/clock/Clock";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <UserProvider>
      <html lang="en">
        <body>
          <div className="mainContent">
            <Clock />
            <div className="d-flex">
              <div className="sidebarSection">
                <Navigation />
              </div>
              {children}
            </div>
          </div>
          <BootstrapClient />
        </body>
      </html>
    </UserProvider>
  );
}
